### ISSUE TITLE
Update default maxMembers for polkadot configuration (on release of pools)

### ISSUE THREAD

**Issue by James-Sangalli** [TalismanSociety/dot-pool-selector#10]
https://github.com/James-Sangalli/dot-pool-selector/blob/main/src/Types.ts#L46

**Comment by jonathanpdunne** [comment]
Information on max members here:

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/extrinsics/decode/0x270a0100e40b540200000000000000000000000100204aa9d101000000000000000000000140000000010040000000
